'use strict';
window.ACE_PDF=(()=>{
 let ready;
 function script(src){return new Promise((resolve,reject)=>{const n=document.createElement('script');n.src=src;n.onload=resolve;n.onerror=reject;document.head.append(n);});}
 async function load(){ready ||= (async()=>{await script('vendor/pdf-lib/pdf-lib.min.js');await script('vendor/fontkit/fontkit.umd.min.js');const fonts=await Promise.all(['DejaVuSans.ttf','DejaVuSans-Bold.ttf'].map(async name=>{const r=await fetch('vendor/fonts/'+name);if(!r.ok)throw Error('Font unavailable');return r.arrayBuffer();}));return fonts;})().catch(e=>{ready=null;throw e;});return ready;}
 async function png(svg){const copy=svg.cloneNode(true);const [, ,w,h]=copy.getAttribute('viewBox').split(' ').map(Number);copy.setAttribute('xmlns','http://www.w3.org/2000/svg');copy.setAttribute('width',w*3);copy.setAttribute('height',h*3);const url=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(copy)],{type:'image/svg+xml'}));try{const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject;img.src=url;});const canvas=document.createElement('canvas');canvas.width=w*3;canvas.height=h*3;canvas.getContext('2d').drawImage(img,0,0);return canvas.toDataURL('image/png');}finally{URL.revokeObjectURL(url);}}
 async function save(review){const bytes=await load();const {PDFDocument,rgb}=PDFLib;const doc=await PDFDocument.create({updateMetadata:false});doc.registerFontkit(fontkit);const regular=await doc.embedFont(bytes[0],{subset:true}),bold=await doc.embedFont(bytes[1],{subset:true});doc.setTitle('ACE Check: '+review.title);const root=ACE_REPORT.print(review);let page,y;const navy=rgb(.08,.18,.31),blue=rgb(.88,.92,.97);
 function newPage(){page=doc.addPage([612,792]);y=752;}
 newPage();
 function ensure(height){if(y-height<46)newPage();}
 function lines(text,font,size,width){const result=[];for(const para of text.split('\n')){let line='';for(const word of para.split(/\s+/)){let pieces=[word];if(font.widthOfTextAtSize(word,size)>width){pieces=[];let part='';for(const char of word){if(font.widthOfTextAtSize(part+char,size)>width){pieces.push(part);part='';}part+=char;}if(part)pieces.push(part);}for(const piece of pieces){const next=line?line+' '+piece:piece;if(font.widthOfTextAtSize(next,size)>width&&line){result.push(line);line=piece;}else line=next;}}result.push(line);}return result;}
 function text(value,size=10,strong=false,shade=false){const font=strong?bold:regular;const wrapped=lines(value,font,size,shade?508:532),height=size*1.45;for(const line of wrapped){ensure(height+8);if(shade)page.drawRectangle({x:40,y:y-height+2,width:532,height:height+5,color:blue});page.drawText(line,{x:shade?48:40,y:y-size,font,size,color:navy});y-=height;}y-=8;}
 async function chart(svg,width=532){const image=await doc.embedPng(await png(svg));const height=image.height/image.width*width;ensure(height+12);page.drawImage(image,{x:40,y:y-height,width,height});y-=height+12;}
 for(const child of root.children){if(child.classList.contains('review-charts')){const graphs=child.querySelectorAll('svg');await chart(graphs[0],532);await chart(graphs[1],155);text(child.querySelector('figcaption').textContent);text(child.querySelector('.chart-note').textContent,9);}else if(child.tagName==='SECTION'){ensure(70);for(const part of child.children)text(part.textContent,part.tagName==='H2'?14:part.tagName==='H3'?11:10,part.tagName.startsWith('H'),part.tagName==='H2');}else if(child.tagName==='svg')await chart(child);else text(child.textContent,child.tagName==='H1'?20:child.tagName==='H2'?14:10,child.tagName.startsWith('H'),child.tagName==='H2');}
 const pages=doc.getPages();pages.forEach((p,i)=>p.drawText(`Page ${i+1} of ${pages.length}`,{x:40,y:25,font:regular,size:8,color:navy}));const output=await doc.save();const url=URL.createObjectURL(new Blob([output],{type:'application/pdf'}));const a=document.createElement('a');a.href=url;a.download='ace-review.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return output;}
 return {save};
})();
