/* Local charts, presentation, and print views. All document content is inserted as text. */
'use strict';
window.ACE_REPORT=(()=>{
 const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
 const svgEl=(tag,attrs={},text)=>{const n=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text!==undefined)n.textContent=text;return n;};
 const colors=['#8391a3','#b56712','#215bc7','#087f72'];
 function svg(w,h,label){const n=svgEl('svg',{viewBox:`0 0 ${w} ${h}`,role:'img','aria-label':label,'font-family':'Arial, sans-serif'});n.append(svgEl('title',{},label));return n;}
 function bars(items){const n=svg(660,items.length*64+35,'Rubric ratings: '+items.map(i=>`${i.name}, ${i.rating} of 3`).join('; '));items.forEach((i,j)=>{const y=j*64;n.append(svgEl('text',{x:8,y:y+19,fill:'#182b44','font-size':16},i.name),svgEl('rect',{x:8,y:y+28,width:525,height:20,rx:4,fill:'#e3eaf4'}),svgEl('rect',{x:8,y:y+28,width:525*i.rating/3,height:20,rx:4,fill:colors[i.rating]}),svgEl('text',{x:545,y:y+44,fill:'#182b44','font-size':17},`${i.rating}/3`));});n.append(svgEl('text',{x:8,y:items.length*64+19,fill:'#182b44','font-size':14},'Each bar shows rubric points earned out of three.'));return n;}
 function pie(earned,total){const n=svg(260,260,`${earned} of ${total} rubric points earned`);n.append(svgEl('circle',{cx:130,cy:130,r:104,fill:'#e3eaf4'}));if(earned===total)n.append(svgEl('circle',{cx:130,cy:130,r:104,fill:'#087f72'}));else if(earned){const angle=earned/total*Math.PI*2,x=130+104*Math.sin(angle),y=130-104*Math.cos(angle);n.append(svgEl('path',{d:`M130 130 L130 26 A104 104 0 ${angle>Math.PI?1:0} 1 ${x} ${y} Z`,fill:'#087f72'}));}n.append(svgEl('circle',{cx:130,cy:130,r:66,fill:'white'}),svgEl('text',{x:130,y:137,'text-anchor':'middle',fill:'#142d4e','font-size':29,'font-weight':'bold'},`${Math.round(earned/total*100)}%`));return n;}
 function charts(r){const box=el('section',undefined,'review-charts');const sum=r.items.reduce((a,i)=>a+i.rating,0),max=r.items.length*3;const bar=el('figure');bar.append(bars(r.items));const p=el('figure');p.append(pie(sum,max),el('figcaption',`${sum} earned · ${max-sum} remaining · ${max} possible`));box.append(bar,p,el('p','Percentages describe documented rubric points, not student achievement.','chart-note'));return box;}
 function snapshot(r){return {...r,items:r.items.map(i=>({...i})),screen:screenData()};}
 function screenData(){const rows=[...document.querySelectorAll('.screen-row')].map(row=>({name:row.querySelector('.screen-name').value,minutes:Math.max(0,Number(row.querySelector('.screen-minutes').value)||0),untimed:row.querySelector('.screen-minutes').value==='',mode:row.querySelector('select').value}));const duration=Math.max(0,Number(document.querySelector('#screen-duration')?.value)||0);const student=rows.filter(r=>r.mode==='student').reduce((s,r)=>s+r.minutes,0),projection=rows.filter(r=>r.mode==='projection').reduce((s,r)=>s+r.minutes,0),offline=rows.filter(r=>r.mode==='offline').reduce((s,r)=>s+r.minutes,0),unclassified=rows.filter(r=>r.mode==='unknown').reduce((s,r)=>s+r.minutes,0);const ratings=[...document.querySelectorAll('.screen-rating')].map(n=>Number(n.value));return {rows,duration,student,projection,offline,unclassified,ratings};}
 const screenCriteria=[['Timing is documented','Can a reviewer account for the planned minutes?',['No activity timing','Some activities timed','Most activities timed','All activities timed and the total reconciles']],['Screen use has a learning purpose','Does each screen activity explain what learners gain from using the screen?',['Purpose absent','Tools listed without learning purpose','Purpose stated for most screen activities','Purpose stated for every screen activity']],['Offline opportunities are planned','Are screen periods balanced with documented discussion, movement, writing, or hands-on work?',['No offline opportunities documented','An offline option is mentioned','Offline activities are timed','Offline activities and transitions are timed']],['Access and alternatives are planned','Can learners participate when a device, connection, or screen use presents a barrier?',['No alternatives documented','Access barriers acknowledged','A usable alternative is described','Alternatives preserve the learning goal and participation']]];
 function screenSummary(s){const accounted=s.student+s.projection+s.offline+s.unclassified;if(!accounted)return 'Screen exposure is not determined: enter timed activities from the lesson plan. Screen-time planning ratings are self-rated and separate from ACE.';return `${s.rows.some(r=>r.name.trim()&&r.untimed)?'Partial estimate: named activities lack durations, so total exposure is not determined. ':''}Logged student device use: ${s.student} min · Teacher projection only: ${s.projection} min · Offline: ${s.offline} min · Unclassified: ${s.unclassified} min. Lesson duration: ${s.duration||'not entered'} min; accounted activity time: ${accounted} min. ${s.duration?accounted>s.duration?'Activity minutes exceed the duration; check overlaps.':accounted<s.duration?`${s.duration-accounted} minutes remain unaccounted for.`:'Activity minutes match the duration.':''} Estimated exposure including projection: ${s.student+s.projection} min. Screen-time planning score: ${Math.round(s.ratings.reduce((a,b)=>a+b,0)/12*100)}/100 (self-rated; separate from ACE).`;}
 function screenPanel(){const panel=el('section',undefined,'screen-panel');panel.id='screen-time-panel';panel.append(el('h3','Screen-time planning check'),el('p','Enter sequential activities and their minutes from the lesson plan. Use student device use for activities that also include projection so minutes are counted once. Projection only means students view a teacher display without using their own device. Unknown timing cannot establish a total. Enter a separate ledger for each learner path when groups do different activities. Include homework only if its time belongs in your stated duration. For a syllabus, assess a specific lesson or session. This is a planning rubric, not a health threshold.'));
 const label=el('label','Lesson duration in minutes');label.htmlFor='screen-duration';const duration=el('input');duration.id='screen-duration';duration.type='number';duration.min=0;duration.max=10000;duration.addEventListener('input',refresh);panel.append(label,duration);const rows=el('div');rows.id='screen-rows';panel.append(rows);const add=el('button','Add timed activity');add.type='button';add.onclick=()=>addRow();panel.append(add);screenCriteria.forEach(([name,meaning,anchors],index)=>{const l=el('label',name);l.htmlFor='screen-rating-'+index;const select=el('select',undefined,'screen-rating');select.id=l.htmlFor;anchors.forEach((text,value)=>{const o=el('option',`${value} · ${text}`);o.value=value;select.append(o);});select.onchange=refresh;panel.append(l,el('p',meaning),select);});const summary=el('p',undefined,'screen-summary');summary.id='screen-summary';summary.setAttribute('aria-live','polite');panel.append(summary);const graph=el('div');graph.id='screen-graph';panel.append(graph);
 function refresh(){if(!document.getElementById('screen-summary'))return;const s=screenData();summary.textContent=screenSummary(s);graph.replaceChildren(bars(screenCriteria.map((c,j)=>({name:c[0],rating:s.ratings[j]}))));}
 function addRow(){const row=el('div',undefined,'screen-row');const name=el('input',undefined,'screen-name');name.placeholder='Activity';name.setAttribute('aria-label','Activity name');const minutes=el('input',undefined,'screen-minutes');minutes.type='number';minutes.min=0;minutes.max=10000;minutes.placeholder='Minutes';minutes.setAttribute('aria-label','Activity minutes');const mode=el('select');mode.setAttribute('aria-label','Screen use');for(const [v,t]of [['unknown','Unclassified'],['student','Student device use'],['projection','Teacher projection only'],['offline','Offline']]){const o=el('option',t);o.value=v;mode.append(o);}const remove=el('button','Remove');remove.type='button';remove.onclick=()=>{row.remove();refresh();};for(const n of [name,minutes,mode])n.addEventListener('input',refresh);row.append(name,minutes,mode,remove);rows.append(row);refresh();}setTimeout(()=>{addRow();refresh();},0);return panel;}
 function print(r){document.getElementById('print-review')?.remove();const root=el('article',undefined,'formatted-review');root.id='print-review';root.append(el('h1','ACE Check: '+r.title),el('p',`${r.complete?'Reviewed':'Preliminary'} design score: ${r.score}/100`,'report-score'),el('p',`Scope: ${r.type} · ${depthHelp[r.depth].label} · Rubric ${version}`),charts(r));for(const i of r.items){const section=el('section',undefined,'report-criterion');section.append(el('h2',`${i.name} · ${i.rating}/3`),el('p',i.meaning),el('p',i.anchors[i.rating]+' — '+i.explanations[i.rating]),el('p','Automatic rationale: '+i.rationale),el('h3','Supporting passages'),el('p',i.evidence||'Not documented.','report-evidence'),el('p','Evidence locations: '+(i.locations.join('; ')||'None')),el('p','Confirmed: '+(i.checked&&(i.rating===0||validateEvidence(i.evidence,r.text))?'yes':'no')),el('p','Next step: '+i.improve));root.append(section);}root.append(el('h2','Next improvements'));r.items.filter(i=>i.rating<3).sort((a,b)=>a.rating-b.rating).slice(0,3).forEach(i=>root.append(el('p',i.name+': '+i.improve)));root.append(el('h2','Screen-time planning'),el('p',screenSummary(r.screen)));r.screen.rows.forEach(row=>root.append(el('p',`${row.name||'Unnamed activity'}: ${row.minutes} min · ${row.mode}`)));screenCriteria.forEach((c,j)=>root.append(el('h3',`${c[0]} · ${r.screen.ratings[j]}/3`),el('p',c[1]+' '+c[2][r.screen.ratings[j]])));root.append(bars(screenCriteria.map((c,j)=>({name:c[0],rating:r.screen.ratings[j]}))),el('p','Screen-time entries and ratings require human review. Missing activity timing cannot establish total exposure.'),el('p','This planning rubric is not independently validated and does not measure student achievement or misconduct.'));document.body.append(root);return root;}
 let dialog,position=0,current,returnFocus;
 function close(){if(dialog?.open)dialog.close();if(document.fullscreenElement===dialog)document.exitFullscreen().catch(()=>{});returnFocus?.focus();}
 function present(r){current=snapshot(r);position=0;returnFocus=document.activeElement;if(!dialog){dialog=el('dialog',undefined,'projection');dialog.setAttribute('aria-label','ACE review presentation');const content=el('div');content.id='projection-content';const controls=el('div',undefined,'projection-controls');for(const [text,handler]of [['Previous',()=>{position--;slide();}],['Next',()=>{position++;slide();}],['Full screen',async()=>{try{await dialog.requestFullscreen();}catch{document.getElementById('projection-status').textContent='Presentation view is active. Full screen is unavailable in this browser.';}}],['Exit presentation',close]]){const b=el('button',text);b.type='button';b.onclick=handler;controls.append(b);}const status=el('p');status.id='projection-status';status.setAttribute('aria-live','polite');dialog.append(content,controls,status);dialog.addEventListener('close',()=>{if(document.fullscreenElement===dialog)document.exitFullscreen().catch(()=>{});returnFocus?.focus();});dialog.addEventListener('keydown',e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();position=e.key==='Home'?0:e.key==='End'?current.items.length+1:position+(e.key==='ArrowRight'?1:-1);slide();}});document.body.append(dialog);}slide();dialog.showModal();}
 function slide(){position=Math.max(0,Math.min(current.items.length+1,position));const box=document.getElementById('projection-content');box.replaceChildren(el('p',`${current.complete?'Reviewed':'Preliminary'} · ${current.title}`,'projection-caption'));if(position===0)box.append(el('h1',`ACE design score: ${current.score}/100`),charts(current));else if(position<=current.items.length){const i=current.items[position-1];box.append(el('h1',i.name),el('div',`${i.rating}/3 · ${i.anchors[i.rating]}`,'projection-rating'),el('p',i.meaning),el('p',i.explanations[i.rating]),el('p','Next step: '+i.improve));}else box.append(el('h1','Screen-time planning'),el('p',screenSummary(current.screen)),bars(screenCriteria.map((c,j)=>({name:c[0],rating:current.screen.ratings[j]}))));document.getElementById('projection-status').textContent=`Slide ${position+1} of ${current.items.length+2} · Use arrow keys to navigate.`;const buttons=dialog.querySelectorAll('button');buttons[0].disabled=position===0;buttons[1].disabled=position===current.items.length+1;}
 return {charts,snapshot,print,present,close,screenPanel,screenSummary};
})();
