/* Shared rubric for the browser review and downloadable skill. */
(function(root){
const rubric = [
 {id:'alignment',name:'Goal-to-task fit',stage:'a',anchors:['No assessable learning goal or no task is stated.','A learning goal and task are stated, but their alignment is unclear.','The task asks students to demonstrate the stated goal.','The goal, task, and success criteria align at the intended SOLO depth.'],improve:'State one assessable outcome, then identify the task and success criteria that show it.'},
 {id:'articulate',name:'Concept explanation',stage:'a',anchors:['No opportunity to reveal concept understanding is described.','Students identify or recall relevant information.','Students explain relevant concepts and provide examples.','Students explain concepts, distinguish examples from non-examples, and receive support for misconceptions.'],improve:'Add a brief explanation with an example. Identify how you will respond to a misconception.'},
 {id:'connect',name:'Reasoned relationships',stage:'c',anchors:['No relationship among ideas is required.','Students name or compare several ideas without explaining their relationship.','Students explain how or why ideas relate, with support.','Students integrate ideas into a coherent explanation and test or revise the relationship.'],improve:'Ask students to explain how two ideas interact, support the relationship, and revise one weak link.'},
 {id:'extend',name:'Bounded generalization',stage:'e',anchors:['No application beyond the original case is described.','Students apply a method to a similar example.','Students apply a principle under changed conditions and explain their reasoning.','Students justify a broader principle or prediction and explain a limit or counterexample.'],improve:'Change an assumption or case. Ask what principle carries over and when it would fail.'},
 {id:'revision',name:'Instruction-to-revision cycle',stage:'a',anchors:['No modeling, useful feedback, or opportunity to act on feedback is described.','Modeling or feedback is mentioned without a clear student action.','Modeling or actionable feedback is paired with student practice or revision.','Students see modeled reasoning, act on specific feedback, and explain how a revision improves their understanding.'],improve:'Model one reasoning move. Give specific feedback, allow revision, and ask what improved.'},
 {id:'check',name:'Individual learning check',stage:'a',anchors:['Only a completed product or group result is assessed.','An individual response is collected, but understanding is not examined.','Students individually explain or apply the intended learning, with an accessible response option.','The individual check reveals the intended depth and informs a stated reteaching or extension decision.'],improve:'Add a brief individual explanation or application. Offer an accessible mode and state how the result guides teaching.'}
];
const data={version:'1.0',rubric}; if(typeof module==='object'&&module.exports)module.exports=data;else root.ACE_RUBRIC=data;
})(globalThis);
