const {chromium}=require(process.env.ACE_PLAYWRIGHT_MODULE||'@playwright/test');
const assert=require('node:assert/strict');const path=require('node:path');
const base=process.env.ACE_BASE_URL||'http://127.0.0.1:4188/';
(async()=>{
const browser=await chromium.launch({headless:true,...(process.env.ACE_BROWSER_PATH?{executablePath:process.env.ACE_BROWSER_PATH}:{})});const page=await browser.newPage();const errors=[];const remote=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(new URL(base).origin)&&!r.url().startsWith('blob:')&&!r.url().startsWith('data:'))remote.push(r.url());});
await page.goto(base+'score.html');assert.equal(await page.locator('#document-file').getAttribute('accept').then(s=>s.includes('.docx')&&s.includes('.pdf')),true);
async function load(name,message){await page.locator('#document-file').setInputFiles(path.join(__dirname,'fixtures',name));await page.waitForFunction(expected=>document.getElementById('file-status').textContent.includes(expected),message,{timeout:30000});assert.equal(await page.getByRole('button',{name:'Create preliminary review'}).isEnabled(),true);}
await page.getByRole('button',{name:'Try a sample lesson'}).click();await load('lesson.pdf','PDF text loaded locally from 2 pages');assert.equal(await page.locator('.rating-card').count(),0);let text=await page.locator('#document-text').inputValue();assert.match(text,/Students will explain a concept/);assert.match(text,/Students connect ideas/);await page.getByRole('button',{name:'Create preliminary review'}).click();assert.equal(await page.locator('.rating-card').count(),6);assert.ok(Number(await page.locator('#score-number').innerText())>0);
const preserved=text;await load('scan.pdf','Run OCR first');assert.equal(await page.locator('#document-text').inputValue(),preserved);await load('locked.pdf','needs a password');assert.equal(await page.locator('#document-text').inputValue(),preserved);
await page.locator('#document-file').setInputFiles({name:'broken.pdf',mimeType:'application/pdf',buffer:Buffer.from('not a PDF')});await page.waitForFunction(()=>document.querySelector('#file-status').textContent.includes('damaged'));assert.equal(await page.locator('#document-text').inputValue(),preserved);
await load('lesson.docx','DOCX text loaded locally');text=await page.locator('#document-text').inputValue();assert.match(text,/Students will explain a concept/);assert.match(text,/Table cell: Students revise/);assert.match(text,/<img src=x/);await page.getByRole('button',{name:'Create preliminary review'}).click();assert.equal(await page.locator('#review-output img').count(),0);assert.equal(await page.evaluate(()=>window.injected),undefined);
await page.locator('#document-file').setInputFiles({name:'broken.docx',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',buffer:Buffer.from('not a DOCX')});await page.waitForFunction(()=>document.querySelector('#file-status').textContent.includes('Could not read this DOCX'));assert.equal(await page.locator('#document-text').inputValue(),text);
await page.locator('#document-file').setInputFiles({name:'legacy.doc',mimeType:'application/msword',buffer:Buffer.from('old Word file')});await page.waitForFunction(()=>document.querySelector('#file-status').textContent.includes('Choose a PDF or DOCX'));assert.equal(await page.locator('#document-text').inputValue(),text);
await page.locator('#document-file').setInputFiles(path.join(__dirname,'fixtures','lesson.pdf'));await page.locator('#document-file').setInputFiles(path.join(__dirname,'fixtures','lesson.docx'));await page.waitForFunction(()=>document.querySelector('#file-status').textContent.includes('DOCX text loaded locally'));assert.match(await page.locator('#document-text').inputValue(),/Table cell/);assert.equal(await page.locator('#review-form').getAttribute('aria-busy'),'false');
await page.setViewportSize({width:375,height:812});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(remote,[]);assert.deepEqual(errors,[]);console.log('PASS: multi-page PDF extraction and scoring, scanned/password/corrupt PDF errors, DOCX paragraphs and tables, corrupt DOCX, unsupported formats, preservation, rapid file changes, local-only requests, and mobile layout.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
